name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: debian-latest
    steps:
    - name: Deploy to <your domain>
      uses: appleboy/ssh-action@master
      with:
        username: admin
        host: 201.46.121.218
        password: Wmbarros@2024!
        script: 'cd /var/www/html/Teste && ./server_deploy.sh'