name: Deploy on Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Test Server
        env:
          REMOTE_PATH: "/var/www/html/Teste"
        if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          cd ~/.ssh
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa wmbarros@201.46.121.218 "mkdir -p $REMOTE_PATH && cd $REMOTE_PATH && git fetch --tags && git checkout ${{ github.ref }} && /usr/bin/docker compose run --rm backend php yii migrate --interactive=0 && /usr/bin/docker compose run --rm backend php yii cache/flush-all"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITHUB_TOKEN }}
