name: Copy Files to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync files to server
        uses: panubo/rsync-action@v2
        with:
          flags: '-avz --delete'
          source: ./
          destination: ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/Teste
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
